"use client";
import {useState} from "react";
import CanvasWebCodecsStudio from "../components/CanvasWebCodecsStudio";
type Song={trackName:string;artistName:string;albumName?:string;duration?:number;plainLyrics?:string;syncedLyrics?:string};
type Action={character:string;action:string;emotion?:string;gesture?:string};
type Scene={number:number;title:string;start:number;end:number;summary:string;emotion:string;setting:string;camera:string;actions:Action[]};
type Story={story_title:string;mode:string;logline:string;theme:string;emotional_arc:string[];characters:{role:string;description:string}[];scenes:Scene[]};
export default function Home(){
const[title,setTitle]=useState("");const[artist,setArtist]=useState("");const[song,setSong]=useState<Song|null>(null);const[story,setStory]=useState<Story|null>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState("");
async function findSong(){setError("");setStory(null);setLoading(true);try{const r=await fetch("/api/lyrics",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({title,artist})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Song lookup failed");setSong(j.song)}catch(e){setError(e instanceof Error?e.message:"Song lookup failed")}finally{setLoading(false)}}
async function deriveStory(){if(!song)return;setError("");setLoading(true);try{const r=await fetch("/api/story",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({song})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Story generation failed");setStory(j.story)}catch(e){setError(e instanceof Error?e.message:"Story generation failed")}finally{setLoading(false)}}
return <div className="shell"><nav className="nav"><div className="brand">🎬 Cartoon <span>Studio</span></div><div className="badge">V8 · Song → Story</div></nav><main className="main"><section className="hero"><div className="eyebrow">AI music visualizer</div><h1>A song should feel like a story.</h1><p>Give Cartoon Studio a song title and artist. It finds available lyrics, understands the emotional arc, then turns it into scenes and physical character performances.</p></section><div className="grid"><section className="card"><h2>Start with a song</h2><label className="label">Song title</label><input className="input" value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Calm Down"/><label className="label">Artist</label><input className="input" value={artist} onChange={e=>setArtist(e.target.value)} placeholder="e.g. Rema"/><button className="primary" onClick={findSong} disabled={loading||!title||!artist}>{loading?"Working…":"Find song & lyrics"}</button>{error&&<p className="error">{error}</p>}</section><section className="card">{song?<><div className="song"><div className="cover">♪</div><div><h2 style={{margin:"0 0 4px"}}>{song.trackName}</h2><div className="muted">{song.artistName} · {song.albumName||"Unknown album"}</div></div></div><p className="muted">{song.duration?Math.round(song.duration)+" seconds · ":""}Lyrics supplied for story analysis</p>{song.plainLyrics&&<details><summary>Lyrics</summary><div className="lyrics">{song.plainLyrics}</div></details>}<button className="primary" style={{marginTop:16}} onClick={deriveStory} disabled={loading}>{loading?"AI Director working…":"🧠 Derive animated story"}</button></>:<div className="muted">Your song analysis will appear here.</div>}</section></div>{story&&<><CanvasWebCodecsStudio story={story}/><section className="card" style={{marginTop:22}}><div className="eyebrow">{story.mode}</div><h2>{story.story_title}</h2><p>{story.logline}</p><p><b>Theme:</b> {story.theme}</p><p><b>Arc:</b> {story.emotional_arc.join(" → ")}</p><h3>Cast</h3>{story.characters.map(c=><div key={c.role} className="scene"><b>{c.role}</b><div className="muted">{c.description}</div></div>)}<h3>Storyboard</h3>{story.scenes.map(s=><div className="scene" key={s.number}><div className="scenehead"><b>Scene {s.number} · {s.title}</b><span className="muted">{s.start}–{s.end}s</span></div><p>{s.summary}</p><div className="muted">{s.emotion} · {s.setting} · {s.camera}</div>{s.actions.map((a,i)=><span className="action" key={i}>{a.character}: {a.action}{a.emotion?" · "+a.emotion:""}{a.gesture?" · "+a.gesture:""}</span>)}</div>)}</section></>}</main></div>}